config/routes.rb
Rails.application.routes.draw do
  resources :communities do
    resource :subscriptions
  end

  resources :submissions do
    member do
      put "upvote", to: "submissions#upvote"
      put "downvote", to: "submissions#downvote"
    end
    resources :comments do
      member do
        put "upvote", to: "comments#upvote"
        put "downvote", to: "comments#downvote"
      end
    end
  end

  devise_for :users
  resources :users, only: [:show], as: "profile"
  root to: "submissions#index"
end

app/models/community.rb
class Community < ApplicationRecord
    
    belongs_to :user
    has_many :submissions
    
    has_many :subscriptions
    has_many :users, through: :subscriptions

    before_save :format_name

    def format_name
        # the ! after gsub modifies the attribute
        self.name.titleize
        self.name.gsub!(' ', '')
    end
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  before_action :set_community, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]


  # GET /communities
  # GET /communities.json
  def index
    @communities = Community.all
  end

  # GET /communities/1
  # GET /communities/1.json
  def show
  end

  # GET /communities/new
  def new
    @community = current_user.communities.build
  end

  # GET /communities/1/edit
  def edit
  end

  # POST /communities
  # POST /communities.json
  def create
    @community = current_user.communities.build(community_params)
    @community.user_id = current_user.id

    respond_to do |format|
      if @community.save
        format.html { redirect_to @community, notice: 'Community was successfully created.' }
        format.json { render :show, status: :created, location: @community }
      else
        format.html { render :new }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /communities/1
  # PATCH/PUT /communities/1.json
  def update
    respond_to do |format|
      if @community.update(community_params)
        format.html { redirect_to @community, notice: 'Community was successfully updated.' }
        format.json { render :show, status: :ok, location: @community }
      else
        format.html { render :edit }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /communities/1
  # DELETE /communities/1.json
  def destroy
    @community.destroy
    respond_to do |format|
      format.html { redirect_to communities_url, notice: 'Community was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_community
      @community = Community.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def community_params
      params.require(:community).permit(:name, :title, :description, :sidebar, :user_id)
    end
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/views/communities/_community.html.erb
<div class="flex flex-wrap items-center justify-between px-4 py-2 card">
    <div class="flex-1">
        <%= link_to community, class: "no-underline text-gray-700" do %>
            <p class="m-0 leading-tight">
                <span class="inline-flex items-center text-xs text-gray-600 no-underline">
                    <%= render_svg "icons/conversation", styles: "w-3 fill-current text-gray-500 mr-1" %>
                    w/ <%= community.name %>
                </span>
            </p>
            <h3 class="m-0 text-base leading-none"><%= community.title %></h3>
        <% end %>
    </div>
    <div class="flex text-xs font-normal">
        <%= link_to community, class: "no-underline " do %>
            <%= render_svg "icons/view", styles: "w-4 fill-current text-gray-500", title: "View" %>
        <% end %>
        
        <% if author_of(community) %>
            <%= link_to edit_community_path(community), class: "no-underline ml-2" do %>
                <%= render_svg "icons/edit", styles: "w-4 fill-current text-gray-500", title: "Edit" %>
            <% end %>
        

            <%= link_to community, class: "no-underline ml-2", method: :delete, data: { confirm: "Are you sure?" } do %>
                <%= render_svg "icons/delete", styles: "w-4 fill-current text-gray-500", title: "Delete" %>
            <% end %>
        <% end %>
    </div>
</div>

app/views/communities/_community_header.html.erb
<div class="text-white bg-purple-600">
  <div class="container p-4 lg:p-10">
    <h1 class="text-lg font-bold lg:text-3xl">w/<%= community.name %></h1>
  </div>
</div>

app/views/communities/_form.html.erb
<%= form_with(model: community, local: true) do |form| %>
  <% if community.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(community.errors.count, "error") %> prohibited this community from being saved:</h2>

      <ul>
        <% community.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-6">
    <%= form.label :name, class:"label" %>
    <%= form.text_field :name, class: "input" %>
  </div>

  <div class="mb-6">
    <%= form.label :title, class:"label" %>
    <%= form.text_field :title, class: "input" %>
  </div>

  <div class="mb-6">
    <%= form.label :description, class:"label" %>
    <%= form.text_area :description, class: "input" %>
  </div>

  <div class="mb-6">
    <%= form.label :sidebar, class:"label" %>
    <%= form.text_area :sidebar, class: "input" %>
  </div>

  <%= form.hidden_field :user_id, value: current_user.id if user_signed_in? %>

  <div class="actions">
    <%= form.submit class: "btn btn-purple btn-small" %>
  </div>
<% end %>

app/views/communities/_sidebar.html.erb
<div class="rounded">
  <div class="px-8 pt-6 pb-8">
    <div class="flex items-center justify-between m-0 leading-tight">
      <span class="inline-flex items-center text-xs text-gray-600 no-underline">
        <%= render_svg 'icons/conversation', styles: "w-3 fill-current text-gray-500 mr-1" %> 
        <span class="ml-1"><%= community.name %></span>
      </span>
      <% if author_of(community) %>
        <%= link_to edit_community_path(community), class: "no-underline mr-2" do %>
          <%= render_svg 'icons/edit', styles: "w-4 fill-current text-gray-500", title: "Edit" %>
        <% end %>
      <% end %>
    </div>
    <h3 class="m-0 text-lg leading-tight"><%= community.title %></h3>

    <div id="subscribed_block" class="my-6">
      <%= render "subscriptions/subscription", community: community %>
    </div>

    <div class="flex flex-wrap items-center justify-start pt-2">
      <div class="w-1/2 border-r border-gray-400">
        <p class="m-0"><%= community.submissions.count %></p>
        <p class="m-0 text-xs">
          <%= pluralize(community.submissions.count, 'Submission') %>
        </p>
      </div>
      <div class="w-1/2 pl-4">
        <p id="subscribed_count"class="m-0"><%= community.subscriptions.count %></p>
        <p class="m-0 text-xs">Subscribers</p>
      </div>
    </div>

    <hr class="border-b border-gray-400" />

    <div class="mb-6 text-sm">
      <%= community.description %>
    </div>

    <hr class="border-b border-gray-400" />

    <div class="mb-6 text-sm">
      <%= community.sidebar %>
    </div>
  </div>
</div>

app/views/communities/edit.html.erb
<% content_for :community_label, "Edit Community" %>

<%= content_for :primary_content do %>
    <div class="px-4 pt-10 lg:p-10">
        <h1 class="mb-6 text-xl font-normal">Editing community <%= @community.name %></h1>
        <%= render "form", community: @community %>
    </div>
<% end %>

<% content_for :secondary_content do %>
    <div class="px-8 pt-6 pb-8">
        <%= render_svg "community", styles: "max-w-full h-auto mb-4" %>
        <h4>Edit a community on Webbit</h4>
        <p class="text-sm italic">Each community requires the following:</p>
        <ul class="mt-1">
            <li>Name</li>
            <li>Title</li>
            <li>Description</li>
        </ul>
    </div>
<% end %>

<%= render "basic_layout" %>

app/views/communities/index.html.erb
<% content_for :community_label, "All communities" %>

<%= content_for :primary_content do %>
  <div class= "px-4 pt-10 pb-10 lg:p10">
    <h1 class= "mb-6 text-xl font-normal">Communities</h1>
    <%= render @communities %>
  </div>
<% end %>

<% content_for :secondary_content do %>
  <div class="px-8 pt-6 pb-8">
    <%= link_to "New Community", new_community_path if user_signed_in? %>
  </div>
<% end %>

<%= render "basic_layout" %>

app/views/communities/new.html.erb
<% content_for :community_label, "Create community" %>

<%= content_for :primary_content do %>
    <div class="px-4 pt-10 lg:p-10">
        <h1 class="mb-6 text-xl font-normal">Create a community</h1>
        <%= render "form", community: @community %>
    </div>
<% end %>

<% content_for :secondary_content do %>
    <div class="px-8 pt-6 pb-8">
        <%= render_svg "community", styles: "max-w-full h-auto mb-4" %>
        <h4>Create a new community on Webbit</h4>
        <p class="text-sm italic">Each community requires the following:</p>
        <ul class="mt-1">
            <li>Name</li>
            <li>Title</li>
            <li>Description</li>
        </ul>
    </div>
<% end %>

<%= render "basic_layout" %>

app/views/communities/show.html.erb
<% content_for :community_label, "w/#{@community.name}" %>

<%= render "community_header", community: @community %>

<% content_for :primary_content do %>
  <% @community.submissions.each do |submission| %>
    <%= render "submissions/submission", submission: submission %>
  <% end %>
<% end %>

<% content_for :secondary_content do %>
  <%= render "sidebar", community: @community %>

<% end %>

<%= render "basic_layout" %>